### ISSUE TITLE
DWC2 chan reuse issue

### ISSUE THREAD

**Issue by sakumisu** [canmv-k230/rtsmart#8]
Hi, I saw this project, and i need to report for you.  Using usb_osal_enter_critical_section before dwc2_chan_alloc can fix reuse problem, See https://github.com/cherry-embedded/CherryUSB/commit/c24eea607736afd3f6d68301ca1a2ccbf6903954, and for common, we use timeout with 0xffffffff to process NAK, thank you.

**Comment by zzy-canaan** [comment]
We will sync this change, thank you.
